// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Index": {
    "title": "Home",
    "description": "This is the home page.",
    "navigateToAbout": "Navigate to about"
  },
  "About": {
    "title": "About",
    "description": "This is the about page."
  }
};
export default messages;